services:
  db-server:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: CustomerOnboardingDB
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin@123
    ports:
      - "3300:3306"
